name: Integration Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start dependencies (docker-compose)
      run: |
         docker-compose up -d  

    - name: Wait for SQL Server container
      uses: jakejarvis/wait-action@master
      with:
          time: '5s'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: TestMSSQL
      env:
        dbProvider: MSSQL
      run: dotnet test --filter FullyQualifiedName~IntegrationTests --verbosity normal
    - name: TestMySQL
      env:
        dbProvider: MySQL
      run: dotnet test --filter FullyQualifiedName~IntegrationTests --verbosity normal
    - name: TestPGSQL
      env:
        dbProvider: PGSQL
      run: dotnet test --filter FullyQualifiedName~IntegrationTests --verbosity normal
    - name: TestSQLite
      env:
        dbProvider: SQLite
      run: dotnet test --filter FullyQualifiedName~IntegrationTests --verbosity normal

