name: Integration Testing

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Start dependencies (docker-compose)
      run: |
         docker-compose up -d  

    - name: Wait for SQL Server container
      uses: jakejarvis/wait-action@master
      with:
          time: '5s'

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
        
    - name: Restore dependencies
      run: dotnet restore

    - name: Build
      run: dotnet build --no-restore

    - name: Test
      run: dotnet test --filter FullyQualifiedName~IntegrationTests --no-build --verbosity normal
